TechNews.Web/Areas/Admin/Controllers/ReviewController.cs
using System;
using System.Linq;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TechNews.DataLayer.Context;
using TechNews.DataLayer.Entities;
using Microsoft.AspNetCore.HttpOverrides;

namespace TechNews.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ReviewController : Controller
    {
        #region Injection

        private TechNewsContext _context;
        public INotyfService _notyfService { get; }

        public ReviewController(TechNewsContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }


        #endregion

        #region Index

        // GET: Reviews
        public ActionResult Index(int itemId,int pageId)
        {
            var reviews = _context.Reviews
                .Where(r => r.ItemId == itemId).ToList();
            ViewBag.ItemTitle = _context.Items.Find(itemId).ItemTitle;
            ViewBag.ItemId = itemId;

            //For Pagination
            int take = 9;
            int skip = (pageId - 1) * take;
            ViewBag.PageCount = (int)Math.Ceiling(reviews.Count() / (double)take);

            return View(reviews.Skip(skip).Take(take).ToList());
        }

        // GET: Reviews
        public ActionResult AllReviewsIndex(int pageId)
        {
            var reviews = _context.Reviews.ToList();

            //For Pagination
            int take = 9;
            int skip = (pageId - 1) * take;
            ViewBag.PageCount = (int)Math.Ceiling(reviews.Count() / (double)take);

            return View(reviews.Skip(skip).Take(take).ToList());
        }

        #endregion

        #region Details

        // GET: Reviews/Details/5
        public ActionResult Details(int id)
        {
            var reviewDetails = _context.Reviews.FirstOrDefault(r => r.ReviewId == id);

            if (reviewDetails == null)
            {
                return NotFound();
            }

            return View(reviewDetails);
        }


        #endregion

        #region CreateNewAnswer

        // GET: Reviews/Create
        public ActionResult Create(int itemId, int parentId)
        {
            //Getting these two from inputs
            ViewBag.ItemId = itemId;
            ViewBag.ParentId = parentId;

            return View();
        }

        // POST: Reviews/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int itemId, int parentId, [Bind("ReviewId", "UserIpAddress", "ReviewTitle", "ReviewDescription", "ReviewDate", "IsPublished", "LikeCount", "DislikeCount", "ParentId", "EmailAddress", "Username", "ItemId")] Review review)
        {
            try
            {

                if (!ModelState.IsValid)
                    return View(review);

                if (itemId != review.ItemId)
                    return NotFound();

                //Specifying required values and adding review to database
                review.UserIpAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();
                review.ReviewDate = DateTime.Now;
                review.LikeCount = 0;
                review.DislikeCount = 0;
                _context.Reviews.Add(review);
                _context.SaveChanges();
                _notyfService.Success("پاسخ شما با موفقیت ثبت شد !");


                return Redirect($"/Admin/Review/Index?itemId={review.ItemId}");
            }
            catch
            {
                _notyfService.Error("مشکلی در ذخیره داده ها رخ داده است ! لطفا با پشتیبانی تماس بگیرید !");
                return View();
            }
        }


        #endregion

        #region UpdateReviewStatus

        // GET: Reviews/Edit/5
        public ActionResult Edit(int id)
        {
            //Getting review details
            var review = _context.Reviews.Find(id);
            if (review == null)
                return NotFound();

            return View(review);
        }

        // POST: Reviews/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind("ReviewId", "UserIpAddress", "ReviewTitle", "ReviewDescription", "ReviewDate", "IsPublished", "LikeCount", "DislikeCount", "ParentId", "EmailAddress", "Username", "ItemId")] Review review)
        {
            try
            {
                //if model was valid then updating review status
                if (!ModelState.IsValid)
                    return View(review);
                if (id != review.ReviewId)
                    return NotFound();

                _context.Reviews.Update(review);
                _context.SaveChanges();
                _notyfService.Success("وضعیت نظر با موفقیت تغییر یافت !");

                return Redirect($"/Admin/Review/Index?itemId={review.ItemId}");
            }
            catch
            {
                _notyfService.Error("مشکلی در ذخیره داده ها رخ داده است ! لطفا با پشتیبانی تماس بگیرید !");
                return View();
            }
        }


        #endregion

        #region RemoveReview

        // GET: Reviews/Delete/5
        public ActionResult Delete(int id)
        {
            var review = _context.Reviews.Find(id);

            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                //Gathering review details and removing it
                var reviewDetails = _context.Reviews.Find(id);
                _context.Reviews.Remove(reviewDetails);
                _context.SaveChanges();
                _notyfService.Success("کامنت مورد نظر با موفقیت حذف شد !");

                return Redirect($"/Admin/Review/Index?itemId={reviewDetails.ItemId}");
            }
            catch
            {
                return View();
            }
        }

        #endregion

        #region QuickReviewAccess
        [Route("/Admin/UnconfirmedReviews")]
        public IActionResult ReviewQuickConfirmationIndex()
        {
            var review = _context.Reviews.Where(r => !r.IsPublished).ToList();
            return View(review);
        }

        public IActionResult ReviewQuickConfirmation(int reviewId)
        {
            var reviewConfirm = _context.Reviews.Find(reviewId);
            if (reviewConfirm != null)
            {
                reviewConfirm.IsPublished = true;
                _context.SaveChanges();
                _notyfService.Success("کامنت با موفقیت تایید شد !");
            }

            return RedirectToAction("ReviewQuickConfirmationIndex");
        }
        public IActionResult QuickDeleteReview(int reviewId)
        {
            var reviewConfirm = _context.Reviews.Find(reviewId);
            if (reviewConfirm != null)
            {
                _context.Reviews.Remove(reviewConfirm);
                _context.SaveChanges();
                _notyfService.Success("کامنت با موفقیت حذف شد !");
            }

            return RedirectToAction("ReviewQuickConfirmationIndex");
        }
        #endregion
    }
}

TechNews.Web/Areas/Admin/Controllers/UserController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AspNetCore;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using TechNews.DataLayer.Context;
using TechNews.DataLayer.Entities;
using TechNews.Utility;
using TechNews.Utility.Generators;
using TechNews.Utility.Security;
using TechNews.Web.Areas.Admin.Models.ViewModels;

namespace TechNews.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {
        #region Injection

        private TechNewsContext _context;
        private IViewRenderService _viewRenderService;
        public INotyfService _notyfService;

        public UserController(TechNewsContext context, IViewRenderService viewRenderService, INotyfService notyfService)
        {
            _context = context;
            _viewRenderService = viewRenderService;
            _notyfService = notyfService;
        }

        #endregion

        #region BindingProperties

        [BindProperty]
        public UserViewModel NewUser { get; set; }


        #endregion

        #region Index

        // GET: User
        public ActionResult Index(int pageId)
        {
            var users = _context.Users.ToList();

            //For Pagination
            int take = 9;
            int skip = (pageId - 1) * take;
            ViewBag.PageCount = (int)Math.Ceiling(users.Count() / (double)take);


            return View(users.Skip(skip).Take(take).ToList());
        }

        #endregion

        #region Details

        // GET: User/Details/5
        public ActionResult Details(int id)
        {
            var user = _context.Users.Find(id);
            return View(user);
        }

        #endregion

        #region CreateNewUser

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync([Bind("UserId", "UserName", "EmailAddress", "PhoneNumber", "ProfilePhoto", "IpAddress", "RegisterDate", "IsActive", "IdentifierCode", "RoleId", "Password")] User users)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(users);

                //Checking if the email was currently existed in the database then throw a massage and do not let registering user
                if (_context.Users.Any(u => u.EmailAddress == users.EmailAddress.ToLower()))
                {
                    _notyfService.Error("آدرس ایمیل تکراری است !");
                    return View(users);
                }

                //Generating new name for profile photo
                var userProfilePhotoName = StringGenerator.GenerateUniqueString();

                //If photo was selected then name it by currently generated name otherwise name it to default.png
                if (NewUser.ProfilePhoto?.Length > 0 && NewUser.ProfilePhoto.IsImage())
                {
                    users.ProfilePhoto = userProfilePhotoName
                                         + Path.GetExtension(NewUser.ProfilePhoto.FileName);
                }
                else
                {
                    users.ProfilePhoto = "Default.png";
                }

                //Filling required values and inserting user
                users.EmailAddress = users.EmailAddress.ToLower();
                users.RegisterDate = DateTime.Now;

                //Hashing password in order to storing in config file
                users.Password = PasswordHelper.EncodePasswordMd5(users.Password);
                users.IdentifierCode = StringGenerator.GenerateUniqueString();

                _context.Users.Add(users);
                await _context.SaveChangesAsync();

                //If the photo was selected then we copying it to server
                if (NewUser.ProfilePhoto?.Length > 0 && NewUser.ProfilePhoto.IsImage())
                {
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(),
                        "wwwroot",
                        "img",
                        "users",
                        userProfilePhotoName + Path.GetExtension(NewUser.ProfilePhoto.FileName)
                        );
                    await using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await NewUser.ProfilePhoto.CopyToAsync(stream);
                    }
                }

                //Checking if the is active wasn't checked then sending an activation email to user email address
                if (!users.IsActive)
                {
                    var body = await _viewRenderService.RenderToStringAsync("Account/Email/_ActivationEmail", users);
                    SendEmail.Send(users.EmailAddress, "ایمیل فعالسازی", body);
                    _notyfService.Success("ساخت حساب کاربری مورد با موفقیت انجام شد و ایمیل فعالسازی برای کاربر ارسال شد !");
                }


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                _notyfService.Error("مشکلی در ارسال داده ها رخ داده است لطفا پارامتر های ورودی و نوع فایل تصویر ورودی را چک کنید !");
                return View();
            }
        }


        #endregion

        #region UpdateUserDetails

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            var user = _context.Users.Find(id);
            return View(user);
        }

        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind("UserId", "UserName", "EmailAddress", "PhoneNumber", "ProfilePhoto", "IpAddress", "RegisterDate", "IsActive", "IdentifierCode", "RoleId", "Password")] User users)
        {
            try
            {
                if (id != users.UserId)
                {
                    return NotFound();
                }

                if (!ModelState.IsValid)
                {
                    return View(users);
                }


                //Getting current old user details
                var currentUserDetails = _context.Users.AsNoTracking()
                    .FirstOrDefault(pg => pg.UserId == id);

                //Checking if user changed the email address then program doesn't let submit a duplicate email address
                if (currentUserDetails.EmailAddress != users.EmailAddress.ToLower())
                {
                    if (_context.Users.Any(u => u.EmailAddress == users.EmailAddress.ToLower()))
                    {
                        _notyfService.Error("آدرس ایمیل تکراری است !");
                        return View(users);
                    }
                    users.EmailAddress = users.EmailAddress.ToLower();
                }

                //Checking if user currently has any photo that is not default then go for delete it
                if (currentUserDetails.ProfilePhoto != "Default.png")
                {
                    //Checking if user want to change the image
                    if (NewUser.ProfilePhoto != null && NewUser.ProfilePhoto.IsImage())
                    {
                        string oldFilePath = Path.Combine(
                            Directory.GetCurrentDirectory(),
                            "wwwroot",
                            "img",
                            "users",
                            currentUserDetails.ProfilePhoto
                        );
                        //Deleting existed image
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }

                    }


                    //Giving new name to image and saving it on server
                    var newImgName = StringGenerator.GenerateUniqueString();
                    var newFilePath = Path.Combine(
                        Directory.GetCurrentDirectory(),
                        "wwwroot",
                        "img",
                        "users",
                        newImgName + Path.GetExtension(NewUser.ProfilePhoto.FileName)
                    );


                    users.ProfilePhoto = newImgName
                                      + Path.GetExtension(NewUser.ProfilePhoto.FileName);

                    using var stream = new FileStream(newFilePath, FileMode.Create);
                    NewUser.ProfilePhoto.CopyTo(stream);
                }
                else
                {
                    users.ProfilePhoto = currentUserDetails.ProfilePhoto;
                }

                //Generating new unique identifier code and updating user
                users.IdentifierCode = StringGenerator.GenerateUniqueString();

                _context.Update(users);
                _context.SaveChanges();
                _notyfService.Success("اطلاعات کاربر با موفقیت تغییر یافت");

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                _notyfService.Error("مشکلی در ارسال داده ها رخ داده است لطفا پارامتر های ورودی و نوع فایل تصویر ورودی را چک کنید !");
                return View();
            }
        }


        #endregion

        #region RemovingUser

        // GET: User/Delete/5
        public ActionResult Delete(int id)
        {
            var user = _context.Users.Find(id);
            if (user == null)
                return NotFound();

            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var user = _context.Users.Find(id);

TechNews.Web/Areas/Admin/Views/Review/AllReviewsIndex.cshtml
@using TechNews.Utility.DateConvertor
@model IEnumerable<TechNews.DataLayer.Entities.Review>

@{
    ViewData["Title"] = "نظرات";
}

<h1>تمامی نظرات</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserIpAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReviewTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReviewDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReviewDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsPublished)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LikeCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DislikeCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserIpAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReviewTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReviewDescription)
            </td>
            <td>
                <span>@item.ReviewDate.ToShamsiDate()</span>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsPublished)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LikeCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DislikeCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td class="allreviewsIndex">
                <a class="btn btn-sm btn-outline-danger" asp-action="Delete" asp-route-id="@item.ReviewId">حذف نظر</a><br/>
                <a class="btn btn-sm btn-outline-success" asp-action="Create" asp-route-itemId="@item.ItemId" asp-route-parentId="@item.ReviewId"> افزودن پاسخ </a>
                <a class="btn btn-sm btn-outline-dark" asp-action="AddToBlackListUsers" asp-controller="User" asp-route-ipAddress="@item.UserIpAddress">افزودن به لیست سیاه</a>
            </td>
        </tr>
    }
    </tbody>
</table>

<!--Paging-->
<div class="col-md-12 text-center">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            @if (ViewBag.PageCount > 1)
            {
                @for (var i = 1; i <= ViewBag.PageCount; i++)
                {
                    <li class="page-item"><a class="page-link" onclick="changePageNo(@i)">@i</a></li>
                }
            }
        </ul>
    </nav>
</div>


<form asp-action="AllReviewsIndex" asp-controller="Review" id="change">
    <input type="hidden" value="1" name="pageId" id="pageNo" />
</form>


<script>
    function changePageNo(pageId)
    {
        $("#pageNo").val(pageId);
        $("#change").submit();
    }
</script>
<!--EndPaging-->

TechNews.Web/Areas/Admin/Views/Review/Delete.cshtml
@using TechNews.Utility.DateConvertor
@model TechNews.DataLayer.Entities.Review

@{
    ViewData["Title"] = "حذف نظر";
}

<h1>حذف نظر</h1>

<h3>آیا از حذف این کامنت اطمینان دارید ؟</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserIpAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserIpAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReviewTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReviewTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReviewDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReviewDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReviewDate)
        </dt>
        <dd class = "col-sm-10">
            <span>@Model.ReviewDate.ToShamsiDate()</span>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsPublished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsPublished)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LikeCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LikeCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DislikeCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DislikeCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
    </dl>
    
    <form asp-action="Delete" asp-route-id="@Model.ReviewId">
        <input type="submit" value="حذف کامنت" class="btn btn-outline-danger" /> |
        <a asp-action="Index" asp-controller="Review" asp-route-itemId="@Model.ItemId">بازگشت به لیست</a>
    </form>
</div>

TechNews.Web/Areas/Admin/Views/Review/Details.cshtml
@using TechNews.Utility.DateConvertor
@model TechNews.DataLayer.Entities.Review

@{
    ViewData["Title"] = "جزئیات";
}

<h1>جزئیات نظر</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserIpAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserIpAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReviewTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReviewTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReviewDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReviewDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReviewDate)
        </dt>
        <dd class = "col-sm-10">
            <span>@Model.ReviewDate.ToShamsiDate()</span>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsPublished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsPublished)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LikeCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LikeCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DislikeCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DislikeCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-sm btn-outline-warning" asp-action="Edit" asp-controller="Review" asp-route-itemId="@Model.ItemId">تغییر وضعیت</a>
    <a asp-action="Create" asp-route-itemId="@Model.ItemId" asp-route-reviewId="@Model.ReviewId" class="btn btn-sm btn-outline-info">افزودن پاسخ</a>
    <a asp-action="Index" asp-controller="Review" asp-route-itemId="@Model.ItemId">بازگشت به لیست</a>
</div>

TechNews.Web/Areas/Admin/Views/Review/Index.cshtml
@using TechNews.Utility.DateConvertor
@model IEnumerable<TechNews.DataLayer.Entities.Review>

@{
    ViewData["Title"] = "نظرات";
}

<h1>نظرات پست (@ViewBag.ItemTitle)</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserIpAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReviewTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReviewDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsPublished)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LikeCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DislikeCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserIpAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReviewTitle)
            </td>
            <td>
                <span>@item.ReviewDate.ToShamsiDate()</span>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsPublished)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LikeCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DislikeCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>

            <td>
                <a asp-action="Details" asp-route-id="@item.ReviewId" class="btn btn-sm btn-outline-success">جزئیات نظر</a>
                <a asp-action="Create" asp-route-itemId="@item.ItemId" asp-route-parentId="@item.ReviewId" class="btn btn-sm btn-outline-info">افزودن پاسخ</a>
                <a asp-action="Edit" asp-route-id="@item.ReviewId" class="btn btn-sm btn-outline-secondary">تغییر وضعیت</a>
                <a asp-action="Delete" asp-route-id="@item.ReviewId" class="btn btn-sm btn-outline-danger">حذف نظر</a>
                <a class="btn btn-sm btn-outline-dark" asp-action="AddToBlackListUsers" asp-controller="User" asp-route-ipAddress="@item.UserIpAddress">افزودن به لیست سیاه</a>
            </td>
        </tr>
}
    </tbody>
</table>

<div class="col-md-12 text-center">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            @if (ViewBag.PageCount > 1)
            {
                @for (var i = 1; i <= ViewBag.PageCount; i++)
                {
                    <li class="page-item"><a class="page-link" onclick="changePageNo(@i)">@i</a></li>
                }
            }
        </ul>
    </nav>
</div>

<!--Paging-->
<form asp-action="Index" asp-controller="Review" id="change">
    <input type="hidden" value="1" name="pageId" id="pageNo" />
</form>


<script>
    function changePageNo(pageId)
    {
        $("#pageNo").val(pageId);
        $("#change").submit();
    }
</script>
<!--EndPaging-->