TechNews.Web/Areas/Admin/Controllers/SearchController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using TechNews.DataLayer.Context;

namespace TechNews.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SearchController : Controller
    {
        private TechNewsContext _context;

        public SearchController(TechNewsContext context)
        {
            _context = context;
        }

        [Route("Admin/Post/Search")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SearchInItems(string q, int pageId)
        {
            ViewBag.PhrasedSearched = q;

            var result = _context.Items
                .Where(i =>
                i.ItemTitle.Contains(q) || i.ItemDescription.Contains(q) || i.ShortDescription.Contains(q))
                .ToList();

            //For Pagination
            int take = 9;
            int skip = (pageId - 1) * take;
            ViewBag.PageCount = (int)Math.Ceiling(result.Count() / (double)take);

            return View(result.Skip(skip).Take(take).ToList());
        }

        [Route("Admin/User/Search")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SearchInUsers(string q, int pageId)
        {
            ViewBag.PhrasedSearched = q;
            var result = _context
                .Users
                .Where(u => u.EmailAddress.Contains(q) || u.UserName.Contains(q) || u.PhoneNumber.Contains(q))
                .ToList();

            //For Pagination
            int take = 9;
            int skip = (pageId - 1) * take;
            ViewBag.PageCount = (int)Math.Ceiling(result.Count() / (double)take);

            return View(result.Skip(skip).Take(take).ToList());
        }
    }
}

TechNews.Web/Controllers/PostController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using TechNews.Core.RequiredMethods;
using TechNews.Core.Services.Interfaces;

namespace TechNews.Web.Controllers
{
    public class PostController : Controller
    {
        private IPostRepository _postRepository;
        private ICategoryRepository _categoryRepository;

        public PostController(IPostRepository postRepository,ICategoryRepository categoryRepository)
        {
            _postRepository = postRepository;
            _categoryRepository = categoryRepository;
        }

        [Route("Post/{itemId}")]
        public IActionResult ShowPost(int itemId)
        {
            return View("_SinglePost",_postRepository.GetItemByItemId(itemId));
        }
        [Route("Category/{categoryId}")]
        public IActionResult ShowPostByCategory(int categoryId,int pageId)
        {
            ViewBag.CategoryTitle = _categoryRepository.GetCategoryTitleByCategoryId(categoryId);

            GetSideCategories sideCategories = new GetSideCategories(_categoryRepository);
            ViewBag.AltCategories = sideCategories.GetSideCategory();

            var postsInCategory = _postRepository.GetPostByCategoryId(categoryId);
            //For Pagination
            int take = 9;
            int skip = (pageId - 1) * take;
            ViewBag.PageCount = (int)Math.Ceiling(postsInCategory.Count() / (double)take);

            return View("_ShowPostInCategories", postsInCategory.Skip(skip).Take(take).ToList());
        }

        [Route("LikePost/{itemId}")]
        public IActionResult LikePost(int itemId)
        {
            _postRepository.LikePost(itemId);
            return Redirect($"/Post/{itemId}");

        }
    }
}

TechNews.Web/Controllers/ReviewController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using TechNews.Core.DTOs;
using TechNews.Core.Services.Interfaces;
using Microsoft.AspNetCore.HttpOverrides;

namespace TechNews.Web.Controllers
{
    public class ReviewController : Controller
    {
        #region Injection

        private IReviewRepository _reviewRepository;
        public INotyfService _notyfService;

        public ReviewController(IReviewRepository reviewRepository, INotyfService notyfService)
        {
            _reviewRepository = reviewRepository;
            _notyfService = notyfService;
        }


        #endregion

        #region AddReview

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddReview(ReviewViewModel review)
        {
            review.UserIpAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();
            if (_reviewRepository.AddReview(review))
            {
                _notyfService.Success("نظر شما با موفقیت ثبت شد و پس از تایید مدیریت در سایت نمایش داده خواهد شد !");
            }
            else
            {
                _notyfService.Error("با عرض پوزش ، شما در لیست کاربران غیرمجاز جهت ثبت نظر هستید و نمیتوانید نظر جدیدی ثبت کنید !");
            }

            return Redirect($"/Post/{review.ItemId}");
        }


        #endregion

        #region ReportReview

        public IActionResult ReportReview(int reviewId, int postId)
        {
            _reviewRepository.ReportReview(reviewId);
            _notyfService.Success("دیدگاه برای بررسی مجدد به مدیریت سایت ارسال شد !");
            return Redirect($"/Post/{postId}");
        }


        #endregion

        #region LikeAndDislikeComment

        public IActionResult LikeComment(int reviewId, int postId)
        {
            _reviewRepository.LikeComment(reviewId);
            return Redirect($"/Post/{postId}");
        }
        public IActionResult DislikeComment(int reviewId, int postId)
        {
            _reviewRepository.DislikeComment(reviewId);
            return Redirect($"/Post/{postId}");
        }

        #endregion

    }
}

TechNews.Web/ViewComponents/CategoriesViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TechNews.Core.Services.Interfaces;

namespace TechNews.Web.ViewComponents
{
    public class CategoriesViewComponent:ViewComponent
    {
        private ICategoryRepository _categoryRepository;

        public CategoriesViewComponent(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;   
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("/Views/ViewComponents/HeaderViewComponent.cshtml", _categoryRepository.GetAllCategories());

        }
    }
}

TechNews.Web/Views/Shared/_AddReview.cshtml
@model TechNews.Core.DTOs.ReviewViewModel
<div></div>
<form asp-action="AddReview" asp-controller="Review" id="formComment">
    <div class="form-row">
        <input type="hidden" asp-for="ItemId" value="@ViewBag.PostId"/>
        <input type="hidden" asp-for="ParentId"/>
        <div class="col-md-6">
            <input asp-for="Username" type="text" class="form-control" placeholder="نام شما">
            <span asp-validation-for="Username" class="text-danger"></span>
        </div>
        <div class="col-md-6">
            <input asp-for="EmailAddress" type="email" class="form-control" placeholder="ایمیل">
            <span asp-validation-for="EmailAddress" class="text-danger"></span>
        </div>
        <div class="col-md-12">
            <input asp-for="Title" type="text" class="form-control" placeholder="عنوان دیدگاه">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="col-md-12">
            <textarea asp-for="Description" class="form-control" placeholder="دیدگاه شما ..."></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="col-md-12">
            <div class="text-left">
                <button class="btn btn-primary">ثبت دیدگاه</button>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TechNews.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TechNews.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TechNews.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TechNews.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TechNews.Web/Views/Shared/_MainLayout.cshtml
@using TechNews.Web.ViewComponents
@using Microsoft.AspNetCore.Mvc.Rendering
<html>
<head>
    <partial name="LayoutPartials/_Sources"/>
</head>
<body>
    <div class="top-bar">
      <partial name="LayoutPartials/_TopBar"/>
    </div>
    <div class="main-header">
        @await Component.InvokeAsync("Categories")
    </div>
    <div class="clear-fix"></div>
    @RenderBody()
    <div class="footer">
       <partial name="LayoutPartials/_Footer"/>
    </div>
    <div class="end-wrapper">
       <partial name="LayoutPartials/_CopyRights"/>
    </div>
    <div class="bg"></div>
    <partial name="LayoutPartials/_Scripts"/>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TechNews.Web/Views/Shared/_Reviews.cshtml
@using TechNews.Utility.DateConvertor
@using TechNews.Core.DTOs
@model IEnumerable<TechNews.Core.DTOs.ReviewViewModel>
<div class="comments_form">
    <h3>دیدگاه ها </h3>
    @if (Model.Any())
    {
        @foreach (var review in Model.Where(r => r.ParentId == null))
        {

            <div class="show-comment">
                <div class="show-comment-inside">
                    <p><i class="fa fa-user">&nbsp; <b>@review.Username :</b><span>(@review.ReviewDate.ToShamsiDate())</span></i></p>
                    <span class="pull-left"><a class="btn btn-default" onclick="ReplyComment(@review.ReviewId)"><i class="fa fa-reply"></i>&nbsp;پاسخ</a></span>
                    <h4><b>@review.Title</b></h4>
                    <p>@review.Description</p>

                    <a class="btn btn-default btnlike" asp-action="LikeComment" asp-controller="Review" asp-route-postId="@review.ItemId" asp-route-reviewId="@review.ReviewId"><i class="fa fa-thumbs-up"></i>&nbsp;@review.LikeCount</a>
                    <a class="btn btn-default btndislike" asp-action="DislikeComment" asp-controller="Review" asp-route-postId="@review.ItemId" asp-route-reviewId="@review.ReviewId"><i class="fa fa-thumbs-down"></i>&nbsp;@review.DislikeCount</a>
                    <a class="btn btn-default pull-left btnreport" asp-action="ReportReview" asp-controller="Review" asp-route-postId="@review.ItemId" asp-route-reviewId="@review.ReviewId"><i class="fa fa-lightbulb-o"></i>&nbsp;گزارش</a>


                    @if (Model.Any(r => r.ParentId == review.ReviewId))
                    {
                        @*<a class="collapse-answer-btn" data-toggle="collapse" data-target=".multi-collapse" aria-expanded="false"><i class="fa fa-arrow-down"></i>&nbsp;مشاهده پاسخ ها</a>
                        *@ <a class="show-answer-btn" onclick="ShowAnswers(@review.ReviewId)"><b><i class="fa fa-arrow-down"></i>&nbsp;نمایش پاسخ ها</b></a>

                        <hr />
                        <div class="collapse multi-collapse" id="collapseComments-@review.ReviewId">
                            @foreach (var subReview in Model.Where(r => r.ParentId == review.ReviewId))
                            {
                                <div class="show-comment-inside">
                                    <p><i class="fa fa-user">&nbsp; <b>@subReview.Username در پاسخ گفته :</b><span>(@subReview.ReviewDate.ToShamsiDate())</span></i></p>
                                    <h4><b>@subReview.Title</b></h4>
                                    <p>@subReview.Description</p>

                                    <a class="btn btn-default btnlike" asp-action="LikeComment" asp-controller="Review" asp-route-postId="@subReview.ItemId" asp-route-reviewId="@subReview.ReviewId"><i class="fa fa-thumbs-up"></i>&nbsp;@subReview.LikeCount</a>
                                    <a class="btn btn-default btndislike" asp-action="DislikeComment" asp-controller="Review" asp-route-postId="@subReview.ItemId" asp-route-reviewId="@subReview.ReviewId"><i class="fa fa-thumbs-down"></i>&nbsp;@subReview.DislikeCount</a>
                                    <a class="btn btn-default pull-left btnreport" asp-action="ReportReview" asp-controller="Review" asp-route-postId="@subReview.ItemId" asp-route-reviewId="@subReview.ReviewId"><i class="fa fa-lightbulb-o"></i>&nbsp;گزارش</a>
                                </div>
                            }
                            <a class="hide-answer-btn" onclick="HideAnswers(@review.ReviewId)"><b><i class="fa fa-arrow-up"></i>&nbsp;پنهان کردن پاسخ ها</b></a>
                        </div>
                    }
                </div>
            </div>

        }


    }
    else
    {
        <div>
            <p class="no-comment">تاکنون دیدگاهی ثبت نشده است !</p>
        </div>
    }
    <hr />
    <h5>دیدگاه شما </h5>
    <div id="write-comment">
        <partial name="_AddReview" model="new ReviewViewModel()" />
    </div>
</div>

<script>

    function HideAnswers(reviewId) {
        $('#collapseComments-'+reviewId).collapse('hide');
    }
    function ShowAnswers(reviewId) {
        $('#collapseComments-'+reviewId).collapse('show');
    }

    function ReplyComment(parentId)
    {
        $("#ParentId").val(parentId);
        document
            .getElementById("write-comment")
            .scrollIntoView({ behavior: "smooth" });
    }

</script>

TechNews.Web/Views/Shared/_ShowPostInCategories.cshtml
@using TechNews.Utility.DateConvertor
@model IEnumerable<TechNews.Core.DTOs.ShowItemsInCategory>
<div class="latest-posts">
    <div class="container-fluid">
        <div class="col-md-9">
            <div class="blog-title-span">
                <span class="title">@ViewBag.CategoryTitle</span>
            </div>
            @if (Model.Any())
            {
                @foreach (var post in Model)
                {
                    <div class="col-md-4">
                        <div class="post-box">
                            <a href="/Post/@post.ItemId">
                                <figure>
                                    <img src="/img/posts/@post.ImageTitle" alt="@post.ItemTitle">
                                    <figcaption class="meta-fig">
                                        <span><i class="fa fa-clock-o"></i>&nbsp;@post.PublishDate.ToShamsiDate()</span>&nbsp;
                                        <span><i class="fa fa-comment-o"></i>&nbsp;@post.ReviewsCount</span>
                                    </figcaption>
                                </figure>
                            </a><div class="text-p">
                                <a href="#">
                                    <h5 class="text-center"><strong>@post.ItemTitle</strong></h5>
                                    <p>
                                        @post.ShortDescription
                                    </p>
                                </a><div class="text-center">
                                    <a class="btn btn-default" href="/Post/@post.ItemId">ادامه مطلب</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <p class="notfounditem">موردی در این دسته بندی یافت نشد !</p>
            }
           
        </div>
        <div class="col-md-3 main-content">
            <div class="l-sidebar">
                <partial name="LayoutPartials/HomeLayoutPartials/_SideCategory" model="@ViewBag.AltCategories"/>
            </div>
        </div>
        <div class="col-md-12 text-center">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    @if (ViewBag.PageCount > 1)
                    {
                        @for (var i = 1; i <= ViewBag.PageCount; i++)
                        {
                            <li class="page-item"><a class="page-link" onclick="changePageNo(@i)">@i</a></li>
                        }
                    }
                </ul>
            </nav>
        </div>
    </div>
</div>

<!--Paging-->
<form asp-action="ShowPostByCategory" id="change">
    <input type="hidden" value="1" name="pageId" id="pageNo" />
</form>


<script>
    function changePageNo(pageId)
    {
        $("#pageNo").val(pageId);
        $("#change").submit();
    }
</script>
<!--EndPaging-->

TechNews.Web/Views/Shared/_SinglePost.cshtml
@using TechNews.Utility.DateConvertor
@{
    Layout = "_MainLayout";
    @model TechNews.DataLayer.Entities.Item

}
@{
    ViewData["Title"] = $"{Model.ItemTitle}";
}

<div class="single_post">
    <div class="container-fluid">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="post_img">
                        <img src="/img/posts/@Model.ItemImage" alt="@Model.ItemTitle">
                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>
            <div class="posts_meta text-center">
                <a onclick="RedirectToComments()"><span><i class="fa fa-comment-o"></i>&nbsp;@Model.Reviews.Count نظر</span></a>
                @foreach (var category in Model.SelectedCategory)
                {
                    <a href="/Category/@category.CategoryId"><span><i class="fa fa-bookmark"></i>&nbsp;@category.Categories.CategoryTitle</span></a>
                }
                <a><span><i class="fa fa-calendar"></i>&nbsp;@Model.ItemSubmitDate.ToShamsiDate()</span></a>
                <a asp-action="LikePost" asp-controller="Post" asp-route-itemId="@Model.ItemId"><span><i class="fa fa-heart"></i>&nbsp;@Model.LikeCount</span></a>
            </div>
            
            <div class="post_content">
                <h4>@Model.ItemTitle</h4>
                <p>@Html.Raw(@Model.ItemDescription)</p>
                <p>کلمات کلیدی :</p>
                @foreach (var tag in Model.Tags)
                {
                    <a class="btn btn-default" asp-action="TagPage" asp-controller="Search" asp-route-tagPhrase="@tag.TagTitle">@tag.TagTitle</a>
                }
                
            </div>
            <div id="redirect-comments">
                @await Component.InvokeAsync("Review",Model.ItemId)
            </div>
            
        </div>
    </div>
</div>
<script>
    function RedirectToComments()
    {
        document
            .getElementById("redirect-comments")
            .scrollIntoView({ behavior: "smooth" });
    }
</script>