TechNews.Web/Areas/Admin/Controllers/HomeController.cs
using System.Linq;
using AspNetCore;
using Microsoft.AspNetCore.Mvc;
using TechNews.DataLayer.Context;

namespace TechNews.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private TechNewsContext _context;

        public HomeController(TechNewsContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            #region RequiredViewBags

            ViewBag.UsersCount = _context.Users.Count();

            ViewBag.NewReviews = _context.Reviews.OrderByDescending(r => r.ReviewDate)
                .Count(r => !r.IsPublished);

            ViewBag.NewTicketsCount = _context.Tickets.OrderByDescending(r => r.AnswerSubmitDate)
                .Count(r => !r.IsAnswered);

            ViewBag.Browsers = _context.Browsers.ToList();

            ViewBag.NewTickets = _context.Tickets
                .OrderByDescending(t => t.TicketSubmitDate)
                .Where(t => !t.IsAnswered)
                .Take(6)
                .ToList();

            ViewBag.NewUsers = _context.Users.OrderByDescending(i => i.RegisterDate).Take(6).ToList();

            #endregion

            return View();
        }
    }
}

TechNews.Web/Areas/Admin/Controllers/TicketController.cs
using System;
using System.Linq;
using AspNetCore;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TechNews.DataLayer.Context;
using TechNews.DataLayer.Entities;

namespace TechNews.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TicketController : Controller
    {
        #region Injection

        private TechNewsContext _context;
        public INotyfService _notyfService { get; set; }


        public TicketController(TechNewsContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        #endregion

        #region Index

        // GET: TicketController
        public ActionResult Index(int pageId)
        {
            var tickets = _context.Tickets.ToList();

            //For Pagination
            int take = 9;
            int skip = (pageId - 1) * take;
            ViewBag.PageCount = (int)Math.Ceiling(tickets.Count() / (double)take);

            return View(tickets.Skip(skip).Take(take).ToList());
        }

        // GET: TicketController
        public ActionResult UnansweredTickets()
        {
            var tickets = _context.Tickets.Where(t=>!t.IsAnswered).ToList();
            return View("Index",tickets);
        }
        #endregion

        #region Details

        // GET: TicketController/Details/5
        public ActionResult Details(int id)
        {
            var ticketDetails = _context.Tickets.Find(id);
            if (ticketDetails == null)
                return NotFound();

            return View(ticketDetails);
        }


        #endregion

        #region UpdateTicketStatus

        // GET: TicketController/Edit/5
        public ActionResult Edit(int id)
        {
            var ticket = _context.Tickets.Find(id);
            return View(ticket);
        }

        // POST: TicketController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind("TicketId", "UserFullName", "UserIpAddress", "UserEmailAddress", "UserPhoneNumber", "TicketTitle", "TicketDescription", "TicketSubmitDate", "TicketUniqueCode", "IsAnswered", "AnswerDescription", "AnswerSubmitDate")] Ticket ticket)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(ticket);
                }

                if (ticket.AnswerSubmitDate == null)
                {
                    ticket.AnswerSubmitDate = DateTime.Now;
                }
                _context.Tickets.Update(ticket);
                _context.SaveChanges();

                _notyfService.Success("وضعیت تیکت با موفقیت به روزرسانی شد !");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        #endregion

        #region RemoveTicket

        // GET: TicketController/Delete/5
        public ActionResult Delete(int id)
        {
            var ticketDetails = _context.Tickets.Find(id);

            return View(ticketDetails);
        }

        // POST: TicketController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var ticketDetails = _context.Tickets.Find(id);

                _context.Tickets.Remove(ticketDetails);
                _context.SaveChanges();
                _notyfService.Success("تیکت مورد نظر با موفقیت حذف شد !");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        #endregion

    }
}

TechNews.Web/Areas/Admin/Controllers/UserController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AspNetCore;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using TechNews.DataLayer.Context;
using TechNews.DataLayer.Entities;
using TechNews.Utility;
using TechNews.Utility.Generators;
using TechNews.Utility.Security;
using TechNews.Web.Areas.Admin.Models.ViewModels;

namespace TechNews.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {
        #region Injection

        private TechNewsContext _context;
        private IViewRenderService _viewRenderService;
        public INotyfService _notyfService;

        public UserController(TechNewsContext context, IViewRenderService viewRenderService, INotyfService notyfService)
        {
            _context = context;
            _viewRenderService = viewRenderService;
            _notyfService = notyfService;
        }

        #endregion

        #region BindingProperties

        [BindProperty]
        public UserViewModel NewUser { get; set; }


        #endregion

        #region Index

        // GET: User
        public ActionResult Index(int pageId)
        {
            var users = _context.Users.ToList();

            //For Pagination
            int take = 9;
            int skip = (pageId - 1) * take;
            ViewBag.PageCount = (int)Math.Ceiling(users.Count() / (double)take);


            return View(users.Skip(skip).Take(take).ToList());
        }

        #endregion

        #region Details

        // GET: User/Details/5
        public ActionResult Details(int id)
        {
            var user = _context.Users.Find(id);
            return View(user);
        }

        #endregion

        #region CreateNewUser

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync([Bind("UserId", "UserName", "EmailAddress", "PhoneNumber", "ProfilePhoto", "IpAddress", "RegisterDate", "IsActive", "IdentifierCode", "RoleId", "Password")] User users)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(users);

                //Checking if the email was currently existed in the database then throw a massage and do not let registering user
                if (_context.Users.Any(u => u.EmailAddress == users.EmailAddress.ToLower()))
                {
                    _notyfService.Error("آدرس ایمیل تکراری است !");
                    return View(users);
                }

                //Generating new name for profile photo
                var userProfilePhotoName = StringGenerator.GenerateUniqueString();

                //If photo was selected then name it by currently generated name otherwise name it to default.png
                if (NewUser.ProfilePhoto?.Length > 0 && NewUser.ProfilePhoto.IsImage())
                {
                    users.ProfilePhoto = userProfilePhotoName
                                         + Path.GetExtension(NewUser.ProfilePhoto.FileName);
                }
                else
                {
                    users.ProfilePhoto = "Default.png";
                }

                //Filling required values and inserting user
                users.EmailAddress = users.EmailAddress.ToLower();
                users.RegisterDate = DateTime.Now;

                //Hashing password in order to storing in config file
                users.Password = PasswordHelper.EncodePasswordMd5(users.Password);
                users.IdentifierCode = StringGenerator.GenerateUniqueString();

                _context.Users.Add(users);
                await _context.SaveChangesAsync();

                //If the photo was selected then we copying it to server
                if (NewUser.ProfilePhoto?.Length > 0 && NewUser.ProfilePhoto.IsImage())
                {
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(),
                        "wwwroot",
                        "img",
                        "users",
                        userProfilePhotoName + Path.GetExtension(NewUser.ProfilePhoto.FileName)
                        );
                    await using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await NewUser.ProfilePhoto.CopyToAsync(stream);
                    }
                }

                //Checking if the is active wasn't checked then sending an activation email to user email address
                if (!users.IsActive)
                {
                    var body = await _viewRenderService.RenderToStringAsync("Account/Email/_ActivationEmail", users);
                    SendEmail.Send(users.EmailAddress, "ایمیل فعالسازی", body);
                    _notyfService.Success("ساخت حساب کاربری مورد با موفقیت انجام شد و ایمیل فعالسازی برای کاربر ارسال شد !");
                }


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                _notyfService.Error("مشکلی در ارسال داده ها رخ داده است لطفا پارامتر های ورودی و نوع فایل تصویر ورودی را چک کنید !");
                return View();
            }
        }


        #endregion

        #region UpdateUserDetails

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            var user = _context.Users.Find(id);
            return View(user);
        }

        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind("UserId", "UserName", "EmailAddress", "PhoneNumber", "ProfilePhoto", "IpAddress", "RegisterDate", "IsActive", "IdentifierCode", "RoleId", "Password")] User users)
        {
            try
            {
                if (id != users.UserId)
                {
                    return NotFound();
                }

                if (!ModelState.IsValid)
                {
                    return View(users);
                }


                //Getting current old user details
                var currentUserDetails = _context.Users.AsNoTracking()
                    .FirstOrDefault(pg => pg.UserId == id);

                //Checking if user changed the email address then program doesn't let submit a duplicate email address
                if (currentUserDetails.EmailAddress != users.EmailAddress.ToLower())
                {
                    if (_context.Users.Any(u => u.EmailAddress == users.EmailAddress.ToLower()))
                    {
                        _notyfService.Error("آدرس ایمیل تکراری است !");
                        return View(users);
                    }
                    users.EmailAddress = users.EmailAddress.ToLower();
                }

                //Checking if user currently has any photo that is not default then go for delete it
                if (currentUserDetails.ProfilePhoto != "Default.png")
                {
                    //Checking if user want to change the image
                    if (NewUser.ProfilePhoto != null && NewUser.ProfilePhoto.IsImage())
                    {
                        string oldFilePath = Path.Combine(
                            Directory.GetCurrentDirectory(),
                            "wwwroot",
                            "img",
                            "users",
                            currentUserDetails.ProfilePhoto
                        );
                        //Deleting existed image
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }

                    }


                    //Giving new name to image and saving it on server
                    var newImgName = StringGenerator.GenerateUniqueString();
                    var newFilePath = Path.Combine(
                        Directory.GetCurrentDirectory(),
                        "wwwroot",
                        "img",
                        "users",
                        newImgName + Path.GetExtension(NewUser.ProfilePhoto.FileName)
                    );


                    users.ProfilePhoto = newImgName
                                      + Path.GetExtension(NewUser.ProfilePhoto.FileName);

                    using var stream = new FileStream(newFilePath, FileMode.Create);
                    NewUser.ProfilePhoto.CopyTo(stream);
                }
                else
                {
                    users.ProfilePhoto = currentUserDetails.ProfilePhoto;
                }

                //Generating new unique identifier code and updating user
                users.IdentifierCode = StringGenerator.GenerateUniqueString();

                _context.Update(users);
                _context.SaveChanges();
                _notyfService.Success("اطلاعات کاربر با موفقیت تغییر یافت");

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                _notyfService.Error("مشکلی در ارسال داده ها رخ داده است لطفا پارامتر های ورودی و نوع فایل تصویر ورودی را چک کنید !");
                return View();
            }
        }


        #endregion

        #region RemovingUser

        // GET: User/Delete/5
        public ActionResult Delete(int id)
        {
            var user = _context.Users.Find(id);
            if (user == null)
                return NotFound();

            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var user = _context.Users.Find(id);

TechNews.Web/Areas/Author/Controllers/HomeController.cs
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using TechNews.DataLayer.Context;

namespace TechNews.Web.Areas.Author.Controllers
{
    [Area("Author")]
    public class HomeController : Controller
    {
        private TechNewsContext _context;

        public HomeController(TechNewsContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            ViewBag.NewReviews = _context.Reviews
                .OrderByDescending(r => r.ReviewDate)
                .Count(r => !r.IsPublished);

            ViewBag.PostAuthorCount = _context.Items
                .Count(i => i.AuthorId == int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)
                    .ToString()));

            return View();
        }
    }
}

TechNews.Web/Areas/Admin/Views/Home/Index.cshtml
@using TechNews.DataLayer.Entities
@using TechNews.Utility.DateConvertor
@{
    ViewData["Title"] = "پنل ادمین";
    List<Browser> listBrowsers = ViewBag.Browsers;
    List<Ticket> listTickets = ViewBag.NewTickets;
    List<User> listUsers = ViewBag.NewUsers;
}

<h1 class="admin-title">پنل ادمین</h1>
<!--Status-->
<div class="row">

    <div class="col-lg-4 col-6">
        <!-- small box -->
        <div class="small-box bg-success-gradient">
            <div class="inner">
                <h3>@ViewBag.UsersCount</h3>
                <p>کاربران ثبت شده</p>
            </div>
            <div class="icon">
                <i class="ion ion-person-add"></i>
            </div>
            <a href="/Admin/User" class="small-box-footer">اطلاعات بیشتر <i class="fa fa-arrow-circle-left"></i></a>
        </div>
    </div>
    <!-- ./col -->

    <div class="col-lg-4 col-6">
        <!-- small box -->
        <div class="small-box bg-warning-gradient">
            <div class="inner">
                <h3>@ViewBag.NewReviews</h3>
                <p>نظرات در انتظار تایید</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="/Admin/UnconfirmedReviews" class="small-box-footer">اطلاعات بیشتر <i class="fa fa-arrow-circle-left"></i></a>
        </div>
    </div>
    <!-- ./col -->

    <div class="col-lg-4 col-6">
        <!-- small box -->
        <div class="small-box bg-danger-gradient">
            <div class="inner">
                <h3>@ViewBag.NewTicketsCount</h3>

                <p>تیکت های در انتظار پاسخ</p>
            </div>
            <div class="icon">
                <i class="ion ion-pie-graph"></i>
            </div>
            <a href="/Admin/Ticket" class="small-box-footer">اطلاعات بیشتر <i class="fa fa-arrow-circle-left"></i></a>
        </div>
    </div>
    <!-- ./col -->
</div>


<!--User Browser Details-->
<div class="card col-12">
    <div class="card-header d-flex p-0 ui-sortable-handle" style="cursor: move;">
        <h3 class="card-title p-3">
            <i class="fa fa-feed mr-1"></i>
            اطلاعات مرورگر های مورد استفاده
        </h3>

    </div><!-- /.card-header -->
    <div class="card-body">
        <div class="tab-content p-0">

            <table class="table">
                <thead>
                    <tr>
                        <th>
                            مرورگر و سیستم عامل مورد استفاده
                        </th>
                        <th>
                            تعداد کاربران
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in listBrowsers)
                    {
                        <tr>
                            <td>
                                @item.BrowserName
                            </td>
                            <td>
                                @item.UsedCount
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<!--New Tickets-->
<div class="card col-12">
    <div class="card-header d-flex p-0 ui-sortable-handle" style="cursor: move;">
        <h3 class="card-title p-3">
            <i class="fa fa-ticket mr-1"></i>
            تیکت های جدید
        </h3>

    </div><!-- /.card-header -->
    <div class="card-body">
        <div class="tab-content p-0">
            
            <table class="table">
                <thead>
                <tr>
                    <th>
                        ارسال کننده تیکت
                    </th>
                    <th>
                        آدرس ایمیل
                    </th>
                    <th>
                        آدرس آیپی
                    </th>
                    <th>
                        عنوان تیکت
                    </th>
                    <th>
                        تاریخ ارسال تیکت
                    </th>
                    <th>
                       
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in listTickets)
                {
                    <tr>
                        <td>
                            @item.UserFullName
                        </td>
                        <td>
                            @item.UserEmailAddress
                        </td>
                        <td>
                            @item.UserIpAddress
                        </td>
                        <td>
                            @item.TicketTitle
                        </td>
                        <td>
                            @item.TicketSubmitDate.ToShamsiDate()
                        </td>
                        <td>
                            <a class="btn btn-sm btn-success btn-admin-index" asp-action="Details" asp-controller="Ticket" asp-route-id="@item.TicketId">پاسخ</a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

<!--New Users-->
<div class="card col-12">
    <div class="card-header d-flex p-0 ui-sortable-handle" style="cursor: move;">
        <h3 class="card-title p-3">
            <i class="fa fa-user-plus mr-1"></i>
            کاربران جدید
        </h3>

    </div><!-- /.card-header -->
    <div class="card-body">
        <div class="tab-content p-0">
            
            <table class="table">
                <thead>
                <tr>
                    <th>
                        نام کاربر
                    </th>
                    <th>
                        آدرس ایمیل
                    </th>
                    <th>
                        آدرس آیپی
                    </th>
                    <th>
                        شماره تماس
                    </th>
                    <th>
                        تاریخ ثبت نام
                    </th>
                    <th>
                        وضعیت فعالسازی حساب کاربری
                    </th>
                    <th>
                       
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in listUsers)
                {
                    <tr>
                        <td>
                            @item.UserName
                        </td>
                        <td>
                            @item.EmailAddress
                        </td>
                        <td>
                            @item.IpAddress
                        </td>
                        <td>
                            @item.PhoneNumber
                        </td>
                        <td>
                            @item.RegisterDate.ToShamsiDate()
                        </td>            
                        <td>
                            @if(item.IsActive)
                            {
                            <span>فعال</span>
                            }
                            else
                            {
                            <span>غیر فعال</span>
                            }
                        </td>
                        <td>
                            <a class="btn btn-sm btn-success btn-admin-index" asp-action="Details" asp-controller="User" asp-route-id="@item.UserId">جزئیات بیشتر</a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>